# Stage 1: Build React app
FROM node:20.7.0-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Use serve to host static files
FROM node:20.7.0-alpine

WORKDIR /app

# 安裝 serve
RUN npm install -g serve

# 複製 build 後的檔案
COPY --from=builder /app/dist .

EXPOSE 5173

CMD ["serve", "-s", ".", "-l", "5173"]
