# sdl-backend-main/Dockerfile.prod
FROM node:22-alpine AS base

WORKDIR /sdl-backend-main
ENV NODE_ENV=production

# Install production dependencies
COPY package*.json ./
# If you use a package-lock.json, consider npm ci --only=production
RUN npm ci --only=production

# Copy application code
COPY . .

# EXPOSE 3000 # Not strictly necessary as docker-compose handles port mapping
CMD ["npm", "start"]
